### ISSUE TITLE
How to get Kate to apply correct highlighting?

### ISSUE THREAD

**Issue by bugger11** [mtorromeo/kate-syntax-files#10]
I installed the vue.xml into /.local/share/katepart5/syntax and the highlighting works fine. However, Kate is not applying the highlighting automatically when I open a file with a .vue extension. I have to apply the highlighting manually. How do I automate that in Kate. (I'm on Arch Linux if that makes any difference.)

**Comment by mtorromeo** [comment]
Try updating the syntax file. I added the mimetype attribute to the language definition, it should help.

**Comment by bugger11** [comment]
That looks like it resolved the issue for me. Thank you. Can I buy you a coffee? BTW, nice profile pic! (Hoping to see VR46 have  a good year.)

**Comment by mtorromeo** [comment]
It's fine, It was an easy fix!
