### ISSUE TITLE
something wrong in python.xml, maybe a bug

### ISSUE THREAD

**Issue by wangliang1989** [mtorromeo/kate-syntax-files#2]
I am on Centos 7.2 gnome.I have tried the kate editor, but some strings has been shown as the same with comments. so I try your work.
but I got a mistake that say something wrong in line 590 with the python.xml

English is not my mother tongue.

**Comment by mtorromeo** [comment]
I updated the python.xml definition from upstream. If the issue persist you can open a new report, thanks.
