### ISSUE TITLE
YAML - incorrect comment show

### ISSUE THREAD

**Issue by tonal** [mtorromeo/kate-syntax-files#4]
In line

```
eee: ?#ddd
```

Key: `eee`
Values: `?#ddd`
But `#ddd` show as comment

**Comment by mtorromeo** [comment]
It works for me. Are you sure you are using the updated syntax definition?

**Comment by tonal** [comment]
Yes. I update yaml.xml
![kate-syntax-yaml](https://cloud.githubusercontent.com/assets/316216/13821982/c8475dae-ebc5-11e5-95b5-50e89e31897e.png)
All values after `?` in keys `reg` show as comment
